site_name: Mee6 documentation
site_url: http://SilBoydens.github.io/Mee6-documentation
repo_url: https://github.com/SilBoydens/Mee6-documentation
repo_name: GitHub
site_author: Sil Boydens
theme: readthedocs
markdown_extensions:
 - admonition
 - attr_list
 - def_list
pages:
  - Home: index.md
  - Example: example.md
  - Custom Commands: Commands.md