site_name: Mee6 Documentation
site_url: http://mee6.github.io/Mee6-documentation
repo_url: https://github.com/mee6/Mee6-documentation
repo_name: Mee6-documentation
site_author: Sil Boydens
theme: readthedocs
markdown_extensions:
 - admonition
 - attr_list
 - def_list
pages:
  - Home: index.md
#  - Example: example.md
  - Custom Commands: Commands.md
  - Variables: Variables.md
  - Levels plugin: Levels.md
  - Experience Per Level: levelxp.md
  - Moderator plugin: Moderator.md
  - Music plugin: Music.md
